name: MintJoomla Documentation Home
permalink: /:categories/:title
exclude: ["./bower.json", "./package.json"]
version: 1.0
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false