name: MintJoomla Documentation Home
markdown: redcarpet
pygments: true
permalink: /:categories/:title
exclude: ['./bower.json', './package.json']
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]